select = ["ALL"]
fix = true
ignore = [
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN102",
    "ANN401",
    "COM812",
    "D202",
    "D204",
    "D205",
    "D400",
    "D401",
    "D406",
    "D407",
    "D415",
    "D417",
    "DTZ",
    "ERA001",
    "G004",
    "I001",
    "PD901",
    "PGH003",
    "PTH123",
    "W291",
    "W292",
    "W293",
]
[per-file-ignores]
"test*.py" = ["S101"]